### PR TITLE
Fix `can_report_unaggregated` trait for LogScore and BrierScore

### LINKED ISSUE #14: Some probabilisitic measures have `can_report_unaggregated = false` instead of `true`
Compare for example `BrierLoss` and `BrierScore` which have different values for the trait.

### LINKED ISSUE #15: Add probability of correct classification (PCC) as an alias for balanced_accuracy
Awesome package!

I was wondering if it might be prudent to add another alias to balanced_accuracy called pcc for probability of correct classification.

See the following reference: https://www.kdnuggets.com/2020/03/interpretable-performance-measure-binary-classifier.html#:~:text=Probability%20of%20correct%20classification%20(PCC)&text=PCC%20tells%20us%20how%20good,%2C%20%5B0%2C1%5D.

Not sure how common this alias is.

### PR DESCRIPTION
**Pull request by ablaom**
To resolve #14. 

Also closes #15.

### CODE REVIEW

File: src/finite.jl [hunk 1]
```diff
@@ -293,7 +293,13 @@ const BalancedAccuracyType = API.FussyMeasure{
     human_name="balanced accuracy",
 )
 
-register(BalancedAccuracy, "balanced_accuracy", "bacc", "bac")
+register(
+    BalancedAccuracy,
+    "balanced_accuracy",
+    "bacc",
+    "bac",
+    "Ppprobability_of_correct_classification",
```
Comment (DoktorMike) [inline src/finite.jl:301]: This is misspelled I believe. "Ppp" -> "p"

Comment (ablaom) [reply src/finite.jl:301]: Yeah, I also caught my error and fixed it in a hot fix: https://github.com/JuliaAI/StatisticalMeasures.jl/pull/24/files
